config/routes.rb
Rails.application.routes.draw do
  resources :golds
  resources :stocks
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gold.rb
class Gold < ApplicationRecord

    def self.goldprice
        url = URI("https://api.collectapi.com/economy/goldPrice")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["content-type"] = 'application/json'
    request["authorization"] = 'apikey 0841HbLiKSHzAkDv77WhZ5:44PRCBq0lIWyFu71yWWbM1'

    response = http.request(request)
    json = JSON.parse(response.body)
    data = json['result']
    data.each do |g|
        altin = Gold.create()
        altin.name = g["name"]
        altin.buy = g["buyingstr"]
        altin.sell = g["sellingstr"]
        altin.save
    end

    end
end

app/models/stock.rb
class Stock < ApplicationRecord



def self.hissesenedi
    url = URI("https://api.collectapi.com/economy/hisseSenedi")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["content-type"] = 'application/json'
    request["authorization"] = 'apikey 0841HbLiKSHzAkDv77WhZ5:44PRCBq0lIWyFu71yWWbM1'

    response = http.request(request)
    json = JSON.parse(response.body)
    data = json['result']
    
    data.each do |d|
        hisse = Stock.create()
        hisse.name = d["text"]
        hisse.hisse = d["code"]
        hisse.hacimstr = d["hacimstr"]
        hisse.hacim = d["hacim"]
        hisse.lastpricestr = d["lastpricestr"]
        hisse.lastprice = d["lastprice"]
        hisse.rate = d["rate"]
        hisse.save
    end       

   
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/golds_controller.rb
class GoldsController < ApplicationController
  before_action :set_gold, only: %i[ show edit update destroy ]

  # GET /golds or /golds.json
  def index
    @golds = Gold.all
  end

  # GET /golds/1 or /golds/1.json
  def show
  end

  # GET /golds/new
  def new
    @gold = Gold.new
  end

  # GET /golds/1/edit
  def edit
  end

  # POST /golds or /golds.json
  def create
    @gold = Gold.new(gold_params)

    respond_to do |format|
      if @gold.save
        format.html { redirect_to gold_url(@gold), notice: "Gold was successfully created." }
        format.json { render :show, status: :created, location: @gold }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /golds/1 or /golds/1.json
  def update
    respond_to do |format|
      if @gold.update(gold_params)
        format.html { redirect_to gold_url(@gold), notice: "Gold was successfully updated." }
        format.json { render :show, status: :ok, location: @gold }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /golds/1 or /golds/1.json
  def destroy
    @gold.destroy

    respond_to do |format|
      format.html { redirect_to golds_url, notice: "Gold was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gold
      @gold = Gold.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gold_params
      params.require(:gold).permit(:name, :buy, :sell)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:name, :hisse, :hacimstr, :hacim, :lastpricestr, :lastprice, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/golds_helper.rb
module GoldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/golds/_form.html.erb
<%= form_with(model: gold) do |form| %>
  <% if gold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gold.errors.count, "error") %> prohibited this gold from being saved:</h2>

      <ul>
        <% gold.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :buy %>
    <%= form.text_field :buy %>
  </div>

  <div class="field">
    <%= form.label :sell %>
    <%= form.text_field :sell %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/golds/edit.html.erb
<h1>Editing Gold</h1>

<%= render 'form', gold: @gold %>

<%= link_to 'Show', @gold %> |
<%= link_to 'Back', golds_path %>

app/views/golds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Altin Fiyati</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Alis</th>
      <th>Satis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @golds.each do |gold| %>
      <tr>
        <td><%= gold.name %></td>
        <td><%= gold.buy %></td>
        <td><%= gold.sell %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/golds/new.html.erb
<h1>New Gold</h1>

<%= render 'form', gold: @gold %>

<%= link_to 'Back', golds_path %>

app/views/golds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gold.name %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @gold.buy %>
</p>

<p>
  <strong>Sell:</strong>
  <%= @gold.sell %>
</p>

<%= link_to 'Edit', edit_gold_path(@gold) %> |
<%= link_to 'Back', golds_path %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to "Stocking", home_index_path , class:"navbar-brand"%> 
  <% if user_signed_in? %>
  


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
       
        </li>
        <li class="nav-item">
        <%= link_to "Hisse Senedi", stocks_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Altin Fiyati", golds_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path , class: "nav-link" %>
        </li>
       
        <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        </ul>
        <% else %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Login", new_user_session_path , class: "nav-link" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Me</h1>
<p>Hello My name is Mehmet </p>

app/views/home/index.html.erb
<h1>Stocking Market</h1>
<p>Ruby on Rails Stocking Project</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Stock Market App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

  <%= render "home/navbar" %>
  <br/><br/>
  <div class="container"> 
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hisse %>
    <%= form.text_field :hisse %>
  </div>

  <div class="field">
    <%= form.label :hacimstr %>
    <%= form.number_field :hacimstr %>
  </div>

  <div class="field">
    <%= form.label :hacim %>
    <%= form.number_field :hacim %>
  </div>

  <div class="field">
    <%= form.label :lastpricestr %>
    <%= form.number_field :lastpricestr %>
  </div>

  <div class="field">
    <%= form.label :lastprice %>
    <%= form.number_field :lastprice %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hisse Senedi </h1>

<table>
  <thead>
    <tr>
      <th>Hisse Adi</th>
      <th>Hisse Kodu</th>
      <th>Hacimstr</th>
      <th>Hacim TL</th>
      <th>Son Fiyat(TL)</th>
      <th>Son Fiyat</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.hisse %></td>
        <td><%= stock.hacimstr %></td>
        <td><%= stock.hacim %></td>
        <td><%= stock.lastpricestr %></td>
        <td><%= stock.lastprice %></td>
        <td><%= stock.rate %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Hisse:</strong>
  <%= @stock.hisse %>
</p>

<p>
  <strong>Hacimstr:</strong>
  <%= @stock.hacimstr %>
</p>

<p>
  <strong>Hacim:</strong>
  <%= @stock.hacim %>
</p>

<p>
  <strong>Lastpricestr:</strong>
  <%= @stock.lastpricestr %>
</p>

<p>
  <strong>Lastprice:</strong>
  <%= @stock.lastprice %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @stock.rate %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>